### ISSUE TITLE
public repository

### ISSUE THREAD

**Issue by bjoernmichels** [marijards/minecraft#1]
Danke für den Zugriff auf das Repository!

Wenn Ihr dieses Repository als **Public-Repository** anbietet, würdet ihr den anderen Mitstudenten ermöglicht reinzuschauen und den Diskussionen zu folgen. Ich würden den Link dann auf openOLAT ankündigen. Dies ist natürlich Euch überlassen, also: optional :smile:

**Comment by marijards** [comment]
Das Repository ist nun public
